/* ==========================================================================
   LEARNIVO — Practice Question Bank Controller & SNS Backend Integration
   ========================================================================== */

document.addEventListener('DOMContentLoaded', () => {
  renderPracticeBank();

  if (window.initBackendStatusBadge) {
    window.initBackendStatusBadge('sns-backend-badge');
  }

  initSNSAdaptiveAssistant();
});

function renderPracticeBank(filterText = '') {
  const container = document.getElementById('practice-questions-grid');
  if (!container) return;

  let questions = LEARNIVO_MOCK_DATA.testQuestions;

  if (filterText) {
    const query = filterText.toLowerCase();
    questions = questions.filter(q => 
      q.text.toLowerCase().includes(query) || 
      q.topic.toLowerCase().includes(query) ||
      q.formula.toLowerCase().includes(query)
    );
  }

  if (questions.length === 0) {
    container.innerHTML = `<div style="grid-column: 1/-1; padding: 2rem; text-align: center; color: var(--secondary-text);">No matching practice questions found.</div>`;
    return;
  }

  container.innerHTML = questions.map(q => `
    <div class="question-card-box">
      <div>
        <div style="display: flex; gap: 0.5rem; margin-bottom: 0.85rem;">
          <span class="course-badge">${q.topic}</span>
          <span class="course-badge" style="background: var(--bg-tertiary); color: var(--dark-text);">${q.difficulty}</span>
        </div>
        <h4 style="font-size: 1.05rem; margin-bottom: 0.75rem; font-family: var(--font-body);">${q.text}</h4>
        <div class="math-formula-box" style="font-size: 1.1rem; padding: 0.75rem;">${q.formula}</div>
      </div>
      <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 1.25rem; padding-top: 0.85rem; border-top: 1px solid var(--border-light);">
        <span style="font-size: 0.8rem; color: var(--secondary-text);">Est. Time: 3 mins</span>
        <a href="test.html?id=${q.id}" class="btn btn-primary btn-sm">Solve Now →</a>
      </div>
    </div>
  `).join('');

  // Search Input Handler
  const searchInput = document.getElementById('practice-search-input');
  if (searchInput && !searchInput.dataset.initialized) {
    searchInput.dataset.initialized = 'true';
    searchInput.addEventListener('input', (e) => renderPracticeBank(e.target.value));
  }
}

/**
 * Initialize Interactive SNS Adaptive Learning Assistant
 */
function initSNSAdaptiveAssistant() {
  const queryBtn = document.getElementById('sns-query-btn');
  const queryInput = document.getElementById('sns-query-input');
  const outputBox = document.getElementById('sns-response-output');

  if (!queryBtn || !queryInput || !outputBox) return;

  const handleSend = async () => {
    const text = queryInput.value.trim();
    if (!text) {
      if (window.showToast) window.showToast('Please enter a math topic or question prompt.', 'warning');
      return;
    }

    queryBtn.disabled = true;
    queryBtn.textContent = 'Connecting SNS Backend...';
    outputBox.style.display = 'block';
    outputBox.innerHTML = `<em>⏳ Transmitting prompt to SNS Workbench backend (<code>https://api.agents.snsihub.ai/webhook/adaptive-learning</code>)...</em>`;

    const res = await window.learnivoAPI.sendAdaptiveRequest({
      message: text,
      topic: text,
      source: 'practice-page'
    });

    queryBtn.disabled = false;
    queryBtn.textContent = 'Ask SNS AI →';

    if (res.success && res.data) {
      const modeLabel = res.mode === 'test-mode' ? 'SNS Workbench Test Mode' : 'SNS Workbench Production';
      outputBox.innerHTML = `
        <div style="color: #10B981; font-weight: 600; margin-bottom: 0.5rem; display: flex; align-items: center; gap: 0.5rem;">
          <span>✅ Adaptive AI Response Received (${modeLabel})</span>
        </div>
        <div>${res.data.output?.recommendation || res.data.output?.items?.[0]?.json?.message || 'Recommendation generated by SNS Adaptive Engine.'}</div>
        <div style="margin-top: 0.5rem; font-size: 0.75rem; color: var(--secondary-text);">Endpoint: <code>${res.endpoint}</code></div>
      `;
    } else {
      const fallbackData = res.fallbackResponse?.output;
      outputBox.innerHTML = `
        <div style="color: #6D3FEA; font-weight: 600; margin-bottom: 0.5rem;">
          💡 Adaptive Learning Guidance (Local Adaptive Engine)
        </div>
        <div>${fallbackData.recommendation}</div>
        <div style="margin-top: 0.5rem; font-size: 0.8rem; color: var(--secondary-text);">
          <strong>Suggested Next Topics:</strong> ${fallbackData.nextTopics.join(', ')}
        </div>
      `;
    }
  };

  queryBtn.addEventListener('click', handleSend);
  queryInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleSend();
  });
}
